### ISSUE TITLE
resolving dependency doesn't work

### ISSUE THREAD

**Issue by FlorianKirmaier** [McFoggy/cssfx#16]
I tried adding the latest release to a project of mine.
It can't find it with Gradle.
Can it be, that the latest release wasn't published properly?

**Comment by McFoggy** [comment]
Hi Florian,

indeed it looks like the latest deliveries didn't ended correctly to central.
I'll have a look today.

**Comment by McFoggy** [comment]
Hum... I republished version 1.1.0 without any error but I can only see it on staging repositories at Sonatype.

I'll ask @TomasMikula (he was holding the org.fxmisc namespace) to have a look if he has access to some more accept/publish button or something else.

**Comment by McFoggy** [comment]
Hum not sure the issue is not on Sonatype side

![image](https://user-images.githubusercontent.com/1119660/60709058-cf22c900-9f0f-11e9-9778-72a9b4cf1258.png)

**Comment by McFoggy** [comment]
[OSSRH-49949](https://issues.sonatype.org/browse/OSSRH-49949) created

**Comment by McFoggy** [comment]
@FlorianKirmaier it should be OK now, thanks for reporting and sorry for the inconvenience.

- java 11 & up : use version `11.0.1`
- java 8 : use version `1.1.1`

see all versions on [central](https://search.maven.org/search?q=g:org.fxmisc.cssfx%20AND%20a:cssfx&core=gav)
