### ISSUE TITLE
When a CSS-File is changed and used afterwards, the unchanged version is used.

### ISSUE THREAD

**Issue by FlorianKirmaier** [McFoggy/cssfx#22]
When a CSS-File is changed and used afterward, the unchanged version is used.

Typical pattern to reproduce:
 * Open Your application
 * Make a change to your css file.
 * Open a stage which uses the changed css file
 * The old unchanged cssfile is used.

**Comment by FlorianKirmaier** [comment]
Both versions 11.1.0 and 11.2.0 have this bug.
So it wasn't introduced by my last PR.

**Comment by McFoggy** [comment]
closed by ee2c47f and 3058dcb
