### ISSUE TITLE
provide module info

### ISSUE THREAD

**Issue by McFoggy** [McFoggy/cssfx#31]
as stated in #30 cssfx is not modular.

we should remedy to that by:

- either fixing the automatic module name
- provide real module-info

Also the module name to expose must be defined:
1. `cssfx` it is the current automatic module name:
    * good for compatibility reasons
    * bad for potential collisions in global namespace
1. `org.fxmisc.cssfx`
    * avoid collisions by using the current groupId namespace
    * bad because out control, domain is owned by [Thomas Mikula](https://github.com/TomasMikula)
1. `fr.brouillard.cssfx`
    * avoid collisions by using an owned groupId namespace
    * its a controlled namespace (including for deployment in central)

**Comment by McFoggy** [comment]
@FlorianKirmaier @rustybox any thought ?

**Comment by FlorianKirmaier** [comment]
I don't think 1 is a good solution.
I would either do 3 combined with refactoring the existing classes or 2. Probably 2 because it's easier and the drawback is relatively small.

**Comment by McFoggy** [comment]
3, with a change to `fr.brouillard.oss.cssfx` (better alignement with all my oss stuff), can be done (AFAIK and unless there is no deep check during sonatype/central deployment) without refactoring (neither maven groupId nor java packages).

The cleanest would really be 3 with refactoring. This is not very huge and brings confidence in the capacity of controlling:
- the deployment: everything is aligned and controlled by me (only me for the moment) at sonatype/central level
- the domain name if required
Of course it brings a binary & source incompatibility on the table !

**Comment by FlorianKirmaier** [comment]
The incompatibility wouldn't be a big problem. Most projects just call CSSFXMonitor.start() so refactoring won't be a huge task.

But it should be consistent with the name of maven dependency which probably takes more time because it requires registering the new domain to maven central. Otherwise it would be quite confusing to use.

**Comment by McFoggy** [comment]
> which probably takes more time because it requires registering the new domain to maven central

No I already own all the rights to `fr.brouillard.oss` for sonatype/central deployments
