### ISSUE TITLE
Linear or Exponential Growth due to unregister logic

### ISSUE THREAD

**Issue by FlorianKirmaier** [McFoggy/cssfx#34]
[CSSFXMonitor](https://github.com/McFoggy/cssfx/blob/master/src/main/java/fr/brouillard/oss/cssfx/impl/CSSFXMonitor.java)
When the following methods are called: registerNode unregisterNode registerNode then the listener of the first registerNode are not cleanedUp. If this process is repeated, more and more listeners get collected ultimately slowing down the application. The same happens for the other register and unregister methods.

Ironically this escalates when I'm opening ScenicView in the same JVM (Without the cssfx inside of ScenicView). Then it slowly slows down until it crashes.

My recommendation is to remove the unregister events entirely like it was done in my original [PR](https://github.com/McFoggy/cssfx/pull/25).
It's really hard to get the unregister logic correct.

I've tested that removing the whole unregister logic fixes the problem.

**Comment by FlorianKirmaier** [comment]
@McFoggy 
Any thoughts about it?
I think it's very hard to fix the "unregister" logic and highly recommend not trying so.

**Comment by FlorianKirmaier** [comment]
@McFoggy 
Any news about it? I kinda need a fix for this problem.
Should I provide a pull request? Should I create my own release?

**Comment by McFoggy** [comment]
@FlorianKirmaier I never refused to look at any PR. If you provide one I'll look at it quickly & carefully.
