### ISSUE TITLE
Replace cssfx's own logging functionality with slf4j

### ISSUE THREAD

**Issue by fireandfuel** [McFoggy/cssfx#43]
Please consider to replace cssfx's own logging functionality with slf4j. It's in order to support the major logging frameworks like log4j2, logback, etc. much easier.

slf4j removes the boilercode inside the user's JavaFX application to translate from cssfx's logger implementation to the major logging frameworks by implementing `fr.brouillard.oss.cssfx.impl.log.CSSFXLogger.Logger` and `fr.brouillard.oss.cssfx.impl.log.CSSFXLogger.LoggerFactory`.

**Comment by dwalluck** [comment]
Couldn't you provide something like a `Slf4jLoggerFactoryImpl` in the main jar then have `slf4j-api` as an optional runtime-only dependency?

**Comment by McFoggy** [comment]
There's really no need to introduce a dependency to `slf4j-api` right now. 
If you want one, then add one in your consumer project and take/adapt the logger factory above.
CSSFX is a library and as such it must not integrate non essential dependencies.

**Comment by dwalluck** [comment]
I don't understand, there would be no dependency.

**Comment by McFoggy** [comment]
I neither do not understand your proposal. 
Please provide a PR so that what you have in mind will be clear and understandable.
Thanks for your interest.
